title: norchops
description: >
  [**norchops.com:**](http://www.norchops.com) better living through software development. Or something.
copyright: David Norcott
sass:
  sass_dir: assets/sass
url: http://localhost:4000
twitter_username: "@davidnorcott"
linkedin_username: "davidnorcott"
#instagram_username:
#pinterest_username:
#flickr_username:
#github_username:  "#"
feed_icon: rss
email: "david.norcott@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 8
