title: norchops.com
description: >
  norchops.com: better living through software development. Or something.
copyright: David Norcott
url: http://www.norchops.com
twitter_username: "@davidnorcott"
linkedin_username: "davidnorcott"
#instagram_username:
#pinterest_username:
#flickr_username:
#github_username:  "#"
feed_icon: rss
email: "david.norcott@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 8
excerpt_separator: <!--more-->